### ISSUE TITLE
Not working in svelte5

### ISSUE THREAD

**Issue by ryoppippi** [invakid404/sveltekit-islands#47]
When components includes snippet syntax, it causes Syntax Error

**Comment by invakid404** [comment]
Hey @ryoppippi, thanks for reporting this! I intend to add Svelte 5 support to this repo soon. As of today, it only supports Svelte 4.

Svelte 5 has quite a few internal differences from Svelte 4, so I'm still determining the scope of this. For example, how you instantiate components is different in Svelte 5, so that needs to change at the very least.

I will keep supporting Svelte 4 in this project since Svelte 5 is not stable yet. The internal details of Svelte 5 may change before its official release, so I don't want to fully commit to it yet. However, I might consider doing this in a beta release.

**Comment by invakid404** [comment]
@ryoppippi Getting basic Svelte 5 support turned out to be easier than expected, but there do indeed appear to be some weird parsing issues, which I'd assume is the issue you're talking about. It isn't related to any Svelte 5 features, though, as I am currently testing this on a codebase that I am migrating from Svelte 4 to Svelte 5. I'll need to look into this more.

**Comment by ryoppippi** [comment]
Thank you for you quick investigation!! If you need help, I'll help you!

**Comment by invakid404** [comment]
@ryoppippi I think I got everything to work in [2.0.0-beta.3](https://www.npmjs.com/package/sveltekit-islands/v/2.0.0-beta.3). I successfully migrated [my personal website](https://invak.id) to Svelte 5, and all islands appear to work as intended.

The parse errors on my end were caused by the fact that `vitePreprocess` no longer preprocesses scripts by default. It seems like you must pass `{ script: true }` to `vitePreprocess` in your Svelte config for it to work. I've updated the README to reflect this.

Let me know if anything is still broken on your end.

**Comment by ryoppippi** [comment]
@invakid404 Thank you for your work.
Actually, it still doesn't work in my website.
I'll create a repro repo later! Thanks

**Comment by invakid404** [comment]
@ryoppippi Sorry to hear that; I'll definitely look into it once you provide a reproduction, it's not unlikely I overlooked something :D

**Comment by ryoppippi** [comment]
I'm trying to create a minimal reproduction. Wait a moment.
Hmm this is wired
